# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julen Urain's Homepage
email: julen@robot-learning.de
description: Julen Urain's website. I try to talk about Robotics, Learning and control.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: theCamusean
github_username:  TheCamusean

# Build settings
markdown: kramdown


collections:
    publications:
              output: true
